name: Develop branch gitflow

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Check branch name
  branch-name-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          # Get the source and target branches for the PR
          SOURCE_BRANCH=$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")
          TARGET_BRANCH=$(jq -r .pull_request.base.ref "$GITHUB_EVENT_PATH")

          echo "Source branch: $SOURCE_BRANCH"
          echo "Target branch: $TARGET_BRANCH"

          if [[ "$SOURCE_BRANCH" =~ ^(main|feature/.*|hotfix/.*|release/[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?)$ ]]; then
            echo "Branch name is valid"
          else
            echo "Invalid branch name. Branches must follow the gitflow naming convention to be allowed to merge into the develop branch."
            exit 1
          fi

  # Check for changes to Python code to avoid running tests unnecessarily
  check-python-changes:
    runs-on: ubuntu-latest
    outputs:
      python-changes: ${{ steps.python-changes.outputs.python-changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for changes to Python code
        id: python-changes
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} | grep -qE '.*\.py$'; then
            echo "::set-output name=python-changes::true"
          else
            echo "::set-output name=python-changes::false"
          fi

  # Run tests on base Python version if Python code has changed
  base-test:
    name: Base Tests - Ubuntu-latest - Python 3.9
    needs: check-python-changes
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'develop' && check-python-changes.outputs.python-changes == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-v1-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction -E optimization

      - name: Run tests
        env:
          MPLBACKEND: Agg
        run: |
          source $VENV
          pytest tests/ --optimization

      - name: Start Terminal and exit
        run: |
          source $VENV
          python terminal.py

  # Run tests on all Python versions on multiple OSes
  tests-python:
    name: Vanilla Python Tests - (${{ matrix.python-version }}, ${{ matrix.os }})
    needs: [base-test, check-python-changes]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest]
        exclude:
          - os: ubuntu-latest
            python-version: "3.9"
    if: github.event.pull_request.base.ref == 'develop' && check-python-changes.outputs.python-changes == 'true'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-v1-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction -E optimization

      - name: List installed packages
        shell: bash -l {0}
        run: |
          source $VENV
          pip list

      - name: Run tests
        env:
          MPLBACKEND: Agg
        run: |
          source $VENV
          pytest tests/ --optimization

      - name: Start Terminal and exit
        run: |
          source $VENV
          python terminal.py
