name: Main branch gitflow

on:
  pull_request:
    types: [opened, synchronize]   
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main_branch_pr_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source and target branches
        run: |
          # Get the source and target branches for the PR
          source_branch=$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")
          target_branch=$(jq -r .pull_request.base.ref "$GITHUB_EVENT_PATH")

          echo "Source branch: $source_branch"
          
          # Use a regular expression to match the pattern of hotfix and release branches
          hotfix_or_release_pattern='^(hotfix/.*|release/[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?)$'

          # Check if the source branch matches the pattern and the target branch is the main branch
          if [[ "$source_branch" =~ $hotfix_or_release_pattern ]] && [ "$target_branch" == "main" ]; then
            echo "PR is from a hotfix or release branch and targeting the main branch"
          else
            echo "PR is not from a hotfix or release branch"
            npx github-script -f .github/scripts/add-review-comment.js "$GITHUB_EVENT_PATH" "Pull requests must be from a hotfix or release branch and target the main branch."
          fi