name: OpenBB GitFlow

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-branch-name:
    name: Enforce branch names on all branches.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Branch name: $GITHUB_REF"
          valid_branch_names=(
            "refs/heads/main"
            "refs/heads/develop"
            "refs/heads/release/\d+.\d+.\d+.*"
            "refs/heads/hotfix/*"
            "refs/heads/feature/*"
          )
          valid=false
          for pattern in "${valid_branch_names[@]}"; do
            if [[ "$GITHUB_REF" =~ $pattern ]]; then
              valid=true
              break
            fi
          done
          if $valid; then
            echo "Branch name is valid."
          else
            echo "Branch name is invalid."
            exit 1
          fi
    
  restrict_branch_pull_requests:
    name: Restrict pull requests to the main and develop branches.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Branch name: $GITHUB_REF"
          if [[ "$GITHUB_REF" =~ ^refs/heads/(main|develop)$ ]]; then
            echo "Branch name is valid."
          else
            echo "Branch name is invalid."
            exit 1
          fi

  check_commit_message:
    runs-on: ubuntu-latest
    steps:
    - name: Check commit message
      id: check_message
      run: |
        # Set the active main branch
        MAIN_BRANCH="main"
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

        # Only check commit messages on main development branch
        if [ "$CURRENT_BRANCH" != "$MAIN_BRANCH" ]; then
          exit 0
        fi

        # Regular expression to validate version tag in commit message
        COMMIT_REGEX='(:[0-9]\.[0-9]\.[0-9])'

        # Error messages
        ERROR_MSG="Error: Aborting commit. Your commit message is missing the version tag. \n Please add a version tag to your commit message. For example: 'fixing bug for forecasting :1.0.0'"

        # Check commit message for version tag
        if ! grep -iqE "$COMMIT_REGEX" "$1"; then
          echo "$ERROR_MSG" 
          exit 1
        fi